In [1]:
# Feature scaling is a crucial machine learning preprocessing step that transforms 
# numerical features to a common range or distribution, preventing variables with larger
# magnitudes from dominating models. It ensures equal contribution from all features, 
# enabling faster convergence in algorithms like gradient descent and better performance 
# in distance-based models like KNN, SVM, and Neural Networks.



# feature sclaing always apllies on training data(features) not on label(output)

In [2]:
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

In [3]:
df = pd.read_csv("housing.csv")

In [4]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [5]:
x = df.drop('median_house_value', axis=1) 
y = df[['median_house_value']]

In [6]:
set(x['ocean_proximity'])

{'<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'}

In [7]:
encode = OneHotEncoder()
encoded = encode.fit_transform(x[['ocean_proximity']])

In [8]:
encoded.toarray()

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.]], shape=(20640, 5))

In [9]:
encoded = pd.DataFrame(encoded.toarray(), columns=['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'], index=x.index)

In [10]:
x = x.join(encoded).drop('ocean_proximity',axis=1)

In [11]:
# now we have two methods for feature scaling
# 1. MinMaxScaler 
# 2. StandardScaler

In [12]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [13]:
#1. MinMaxScaler - it is very simple feature scaling technique in which we give the scale
# like give values between 0-1, 0-10 , -1 - 1, 100-3897, etc. 
# formula = (x-min)/(max-min) 

# but in this approach if there is any outlier then outlier may impact the scale which is not good 
# ex if we have student weight if there is outlier like 975 it will become the max and
# aside from it we have weights like in between 40-100 so the outlier may impact the scale 

# Sensitive to outliers — extreme values can distort the scale.

In [14]:
m = MinMaxScaler(feature_range=(-1,1))
minmax = m.fit_transform(x)

In [15]:
minmax

array([[-0.57768924,  0.13496281,  0.56862745, ..., -1.        ,
         1.        , -1.        ],
       [-0.57569721,  0.13071201, -0.21568627, ..., -1.        ,
         1.        , -1.        ],
       [-0.57968127,  0.12858661,  1.        , ..., -1.        ,
         1.        , -1.        ],
       ...,
       [-0.37649402,  0.46439957, -0.37254902, ..., -1.        ,
        -1.        , -1.        ],
       [-0.39641434,  0.46439957, -0.33333333, ..., -1.        ,
        -1.        , -1.        ],
       [-0.38047809,  0.45164718, -0.41176471, ..., -1.        ,
        -1.        , -1.        ]], shape=(20640, 13))

In [16]:
minmax = pd.DataFrame(minmax, columns=x.columns, index=x.index)

In [17]:
minmax

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
0,-0.577689,0.134963,0.568627,-0.955339,-0.960273,-0.982118,-0.958888,0.079337,-1.0,-1.0,-1.0,1.0,-1.0
1,-0.575697,0.130712,-0.215686,-0.638995,-0.657045,-0.865579,-0.626048,0.076054,-1.0,-1.0,-1.0,1.0,-1.0
2,-0.579681,0.128587,1.000000,-0.925479,-0.941341,-0.972365,-0.942115,-0.067944,-1.0,-1.0,-1.0,1.0,-1.0
3,-0.581673,0.128587,1.000000,-0.935297,-0.927374,-0.968889,-0.928301,-0.290603,-1.0,-1.0,-1.0,1.0,-1.0
4,-0.581673,0.128587,1.000000,-0.917341,-0.913408,-0.968497,-0.915146,-0.538448,-1.0,-1.0,-1.0,1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-0.350598,0.475027,-0.058824,-0.915408,-0.884233,-0.952801,-0.891794,-0.853740,-1.0,1.0,-1.0,-1.0,-1.0
20636,-0.374502,0.477152,-0.333333,-0.964647,-0.953755,-0.980212,-0.962835,-0.716294,-1.0,1.0,-1.0,-1.0,-1.0
20637,-0.376494,0.464400,-0.372549,-0.885447,-0.849783,-0.943720,-0.857918,-0.834471,-1.0,1.0,-1.0,-1.0,-1.0
20638,-0.396414,0.464400,-0.333333,-0.905489,-0.873371,-0.958631,-0.885545,-0.811409,-1.0,1.0,-1.0,-1.0,-1.0
20639,-0.380478,0.451647,-0.411765,-0.858436,-0.809125,-0.922419,-0.826015,-0.739493,-1.0,1.0,-1.0,-1.0,-1.0

In [18]:
# 2. StandardScaler (Z-score)
# This method centers the data around 0 and scales it based on standard deviation.
# it can handle outliers because it work with mean and the standard deviation of the feature

In [19]:
stand = StandardScaler()

In [20]:
stand = stand.fit_transform(x)

In [21]:
stand

array([[-1.32783522,  1.05254828,  0.98214266, ..., -0.01556621,
         2.83074203, -0.38446649],
       [-1.32284391,  1.04318455, -0.60701891, ..., -0.01556621,
         2.83074203, -0.38446649],
       [-1.33282653,  1.03850269,  1.85618152, ..., -0.01556621,
         2.83074203, -0.38446649],
       ...,
       [-0.8237132 ,  1.77823747, -0.92485123, ..., -0.01556621,
        -0.35326426, -0.38446649],
       [-0.87362627,  1.77823747, -0.84539315, ..., -0.01556621,
        -0.35326426, -0.38446649],
       [-0.83369581,  1.75014627, -1.00430931, ..., -0.01556621,
        -0.35326426, -0.38446649]], shape=(20640, 13))

In [22]:
stand = pd.DataFrame(stand, columns=x.columns, index=x.index)

In [23]:
stand

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
0,-1.327835,1.052548,0.982143,-0.804819,-0.970325,-0.974429,-0.977033,2.344766,-0.891156,-0.681889,-0.015566,2.830742,-0.384466
1,-1.322844,1.043185,-0.607019,2.045890,1.348276,0.861439,1.669961,2.332238,-0.891156,-0.681889,-0.015566,2.830742,-0.384466
2,-1.332827,1.038503,1.856182,-0.535746,-0.825561,-0.820777,-0.843637,1.782699,-0.891156,-0.681889,-0.015566,2.830742,-0.384466
3,-1.337818,1.038503,1.856182,-0.624215,-0.718768,-0.766028,-0.733781,0.932968,-0.891156,-0.681889,-0.015566,2.830742,-0.384466
4,-1.337818,1.038503,1.856182,-0.462404,-0.611974,-0.759847,-0.629157,-0.012881,-0.891156,-0.681889,-0.015566,2.830742,-0.384466
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-0.758826,1.801647,-0.289187,-0.444985,-0.388895,-0.512592,-0.443449,-1.216128,-0.891156,1.466514,-0.015566,-0.353264,-0.384466
20636,-0.818722,1.806329,-0.845393,-0.888704,-0.920488,-0.944405,-1.008420,-0.691593,-0.891156,1.466514,-0.015566,-0.353264,-0.384466
20637,-0.823713,1.778237,-0.924851,-0.174995,-0.125472,-0.369537,-0.174042,-1.142593,-0.891156,1.466514,-0.015566,-0.353264,-0.384466
20638,-0.873626,1.778237,-0.845393,-0.355600,-0.305834,-0.604429,-0.393753,-1.054583,-0.891156,1.466514,-0.015566,-0.353264,-0.384466
20639,-0.833696,1.750146,-1.004309,0.068408,0.185416,-0.033977,0.079672,-0.780129,-0.891156,1.466514,-0.015566,-0.353264,-0.384466

In [ ]:
#there are more scaling methods

# one hot encoding is not useful if we have no. categories it make no. columns for them which make dataset large and slow for model 

# target encoding : 
# in it we are assigning the mean value the categories but in this approach there is a chace of data leakage and overfitting because we are using both features and label
# so preventing the these we can use K-FOLD ENCODING

# Binary encoding and Hash Encoding