In [1]:
# as we are handling null values and apllying feature scaling to train the model. 
# so need to fit_transform every time for each problem.

# sklearn provided us pipelearn to do work in a structural and efficient way.

In [1]:
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

In [2]:
df = pd.read_csv("housing.csv")

In [3]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [4]:
x = df.drop('median_house_value', axis=1) 
y = df['median_house_value']

In [5]:
x.drop('ocean_proximity', axis=1, inplace=True)

In [6]:
# now i removed the categorical data for easy understanding of the pipeline

In [7]:
from sklearn.pipeline import Pipeline

In [8]:
pipe = Pipeline([
    ('imputation', SimpleImputer(strategy='median')),
    ('standardization', StandardScaler()),
])

# here we are impute and then standardize the values. 
# it creates a chain of work like first it do imputaion and then it do standardization
# and we can name the process like i wrote 'imputation' and 'standardization'. if we not want to na,e them 
# then we can use make_pipeline function : 

# from sklearn.pipeline import make_pipeline
# make = make_pipeline(SimpleImputer(strategy='meadian'), StandardScaler())

In [9]:
# How It Works

# The pipeline takes a list of steps as (name, transformer) pairs.
# Names must be unique and should not contain double underscores __.
# All intermediate steps must be transformers (i.e., must implement fit_transform()).
# The final step can be either a transformer or a predictor.

In [10]:
pipe = pipe.fit_transform(x)

In [11]:
pipe = pd.DataFrame(pipe, columns=x.columns, index=x.index)

In [12]:
pipe

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
0,-1.327835,1.052548,0.982143,-0.804819,-0.972476,-0.974429,-0.977033,2.344766
1,-1.322844,1.043185,-0.607019,2.045890,1.357143,0.861439,1.669961,2.332238
2,-1.332827,1.038503,1.856182,-0.535746,-0.827024,-0.820777,-0.843637,1.782699
3,-1.337818,1.038503,1.856182,-0.624215,-0.719723,-0.766028,-0.733781,0.932968
4,-1.337818,1.038503,1.856182,-0.462404,-0.612423,-0.759847,-0.629157,-0.012881
...,...,...,...,...,...,...,...,...
20635,-0.758826,1.801647,-0.289187,-0.444985,-0.388283,-0.512592,-0.443449,-1.216128
20636,-0.818722,1.806329,-0.845393,-0.888704,-0.922403,-0.944405,-1.008420,-0.691593
20637,-0.823713,1.778237,-0.924851,-0.174995,-0.123608,-0.369537,-0.174042,-1.142593
20638,-0.873626,1.778237,-0.845393,-0.355600,-0.304827,-0.604429,-0.393753,-1.054583
20639,-0.833696,1.750146,-1.004309,0.068408,0.188757,-0.033977,0.079672,-0.780129