In [1]:
import numpy as np 
import pandas as pd

In [2]:
# creating a data frame though python list
lis = [['Aman', 89], ['Anurag', 67], ['Jishan', 70], ['Abhay', 69]]

In [3]:
df = pd.DataFrame(lis, columns=['Name', 'Marks'])
df

     Name  Marks
0    Aman     89
1  Anurag     67
2  Jishan     70
3   Abhay     69

In [4]:
# data frame using dictionary
dic = {'Name' : ['Aman', 'Golu', 'Jishan', 'Yogender'],
      'KD' : [3.52, 2.54, 4.16, 5.37]}

In [5]:
df = pd.DataFrame(dic)
df

       Name    KD
0      Aman  3.52
1      Golu  2.54
2    Jishan  4.16
3  Yogender  5.37

In [8]:
# data frame using numpy array 
arr = np.array([[3.52,296], [2.42, 248], [4.16, 267], [5.24, 296]])

In [9]:
df = pd.DataFrame(arr, columns=['KD', 'Tot. Matches'])
df

     KD  Tot. Matches
0  3.52         296.0
1  2.42         248.0
2  4.16         267.0
3  5.24         296.0